Repository YAPP-Github/21st-Android-Team-1-Android, pull requests merged in 2023-01, with the labels that each got.

#10 [Resource] setting
  presentation/src/main/res/drawable/ic_back.xml
  presentation/src/main/res/drawable/ic_fab_cancle.xml
  presentation/src/main/res/drawable/ic_fab_plus.xml
  presentation/src/main/res/font/pretendard_bold.otf
  presentation/src/main/res/font/pretendard_medium.otf
  presentation/src/main/res/font/pretendard_regular.otf
  presentation/src/main/res/layout/activity_buddy_con.xml
  presentation/src/main/res/layout/layout_appbar.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/text_style.xml
Labels: design

#13 Feature/home fab
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/addCoupon/AddCouponActivity.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/main/BuddyConActivity.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/main/BuddyConViewModel.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/makeCoupon/MakeCouponActivity.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/splash/SplashActivity.kt
  presentation/src/main/res/drawable/bg_fab_menu.xml
  presentation/src/main/res/drawable/btn_add_coupon.xml
  presentation/src/main/res/drawable/btn_fab_cancle.xml
  presentation/src/main/res/drawable/btn_fab_plus.xml
  presentation/src/main/res/drawable/btn_make_coupon.xml
  presentation/src/main/res/drawable/ic_fab_cancle.xml
  presentation/src/main/res/layout/activity_add_coupon.xml
  presentation/src/main/res/layout/activity_buddy_con.xml
  presentation/src/main/res/layout/activity_make_coupon.xml
  presentation/src/main/res/layout/layout_appbar.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, design

#20 Feat/kakao login 카카오 로그인 기능 개발
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yapp/buddycon/BuddyConApplication.kt
  buildSrc/src/main/java/Dependency.kt
  data/src/main/java/com/yapp/buddycon/data/datasource/remote/dummy
  data/src/main/java/com/yapp/buddycon/data/datasource/remote/login/LoginRemoteDataSource.kt
  data/src/main/java/com/yapp/buddycon/data/datasource/remote/login/LoginRemoteDataSourceImpl.kt
  data/src/main/java/com/yapp/buddycon/data/di/DataSourceModule.kt
  data/src/main/java/com/yapp/buddycon/data/di/InterceptorModule.kt
  data/src/main/java/com/yapp/buddycon/data/di/NetworkModule.kt
  data/src/main/java/com/yapp/buddycon/data/di/RepositoryModule.kt
  data/src/main/java/com/yapp/buddycon/data/mapper/dummy
  data/src/main/java/com/yapp/buddycon/data/mapper/mapper.kt
  data/src/main/java/com/yapp/buddycon/data/network/api/LoginService.kt
  data/src/main/java/com/yapp/buddycon/data/network/api/dummy
  data/src/main/java/com/yapp/buddycon/data/network/interceptor/BuddyConInterceptor.kt
  data/src/main/java/com/yapp/buddycon/data/network/qualifiers/DispatcherQualifiers.kt
  data/src/main/java/com/yapp/buddycon/data/network/qualifiers/InterceptorQualifiers.kt
  data/src/main/java/com/yapp/buddycon/data/network/qualifiers/OkHttpClientQualifiers.kt
  data/src/main/java/com/yapp/buddycon/data/network/qualifiers/RetrofitQualifiers.kt
  data/src/main/java/com/yapp/buddycon/data/network/response/UserInfoResponse.kt
  data/src/main/java/com/yapp/buddycon/data/network/response/dummy
  data/src/main/java/com/yapp/buddycon/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/yapp/buddycon/data/repository/dummy
  domain/build.gradle.kts
  domain/src/main/java/com/yapp/buddycon/domain/model/UserInfo.kt
  domain/src/main/java/com/yapp/buddycon/domain/model/dummy
  domain/src/main/java/com/yapp/buddycon/domain/repository/LoginRepository.kt
  domain/src/main/java/com/yapp/buddycon/domain/repository/dummy
  domain/src/main/java/com/yapp/buddycon/domain/usecase/GetUserInfoUseCase.kt
  domain/src/main/java/com/yapp/buddycon/domain/usecase/dummy
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/login/KaKaoLoginState.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/login/KaKaoLoginViewModel.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/login/KakaoLoginActivity.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/splash/SplashActivity.kt
  presentation/src/main/res/drawable-hdpi/bg_kakao_login.png
  presentation/src/main/res/drawable-hdpi/img_buddycon.png
  presentation/src/main/res/drawable-mdpi/bg_kakao_login.png
  presentation/src/main/res/drawable-mdpi/img_buddycon.png
  presentation/src/main/res/drawable-xhdpi/bg_kakao_login.png
  presentation/src/main/res/drawable-xhdpi/img_buddycon.png
  presentation/src/main/res/drawable-xxhdpi/bg_kakao_login.png
  presentation/src/main/res/drawable-xxhdpi/img_buddycon.png
  presentation/src/main/res/drawable-xxxhdpi/bg_kakao_login.png
  presentation/src/main/res/drawable-xxxhdpi/img_buddycon.png
  presentation/src/main/res/font/raleway_bold.ttf
  presentation/src/main/res/layout/activity_buddy_con.xml
  presentation/src/main/res/layout/activity_kakao_login.xml
  presentation/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: feature

#22 Feat/dataStore 카카오 로그인 연동 후 BuddyCon 서버 액세스 토큰 DataStore에 저장
  data/src/main/java/com/yapp/buddycon/data/di/DataStoreModule.kt
  data/src/main/java/com/yapp/buddycon/data/di/RepositoryModule.kt
  data/src/main/java/com/yapp/buddycon/data/repository/TokenRepositoryImpl.kt
  domain/src/main/java/com/yapp/buddycon/domain/repository/TokenRepository.kt
  domain/src/main/java/com/yapp/buddycon/domain/usecase/SaveTokenUseCase.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/login/KaKaoLoginViewModel.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/login/KakaoLoginActivity.kt
Labels: feature

#36 Feat/login access token 카카오 로그인 후 토큰 만료일에 따른 화면 분기 및 회원가입 화면 노출
  data/src/main/java/com/yapp/buddycon/data/mapper/mapper.kt
  data/src/main/java/com/yapp/buddycon/data/network/response/UserInfoResponse.kt
  data/src/main/java/com/yapp/buddycon/data/repository/TokenRepositoryImpl.kt
  domain/src/main/java/com/yapp/buddycon/domain/model/UserInfo.kt
  domain/src/main/java/com/yapp/buddycon/domain/repository/TokenRepository.kt
  domain/src/main/java/com/yapp/buddycon/domain/usecase/GetTokenUseCase.kt
  domain/src/main/java/com/yapp/buddycon/domain/usecase/SaveTokenUseCase.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/login/KaKaoLoginViewModel.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/login/KakaoLoginActivity.kt
  presentation/src/main/res/drawable-hdpi/bg_signup.png
  presentation/src/main/res/drawable-mdpi/bg_signup.png
  presentation/src/main/res/drawable-xhdpi/bg_signup.png
  presentation/src/main/res/drawable-xxhdpi/bg_signup.png
  presentation/src/main/res/drawable-xxxhdpi/bg_signup.png
  presentation/src/main/res/layout/activity_kakao_login.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/text_style.xml
Labels: feature

#49 Feature/제작티콘 만들기 테마 변경 적용
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/makeCoupon/MakeCouponActivity.kt
  presentation/src/main/java/com/yapp/buddycon/presentation/ui/makeCoupon/MakeCouponViewModel.kt
  presentation/src/main/res/drawable-hdpi/bg_theme1.png
  presentation/src/main/res/drawable-hdpi/bg_theme2.png
  presentation/src/main/res/drawable-hdpi/bg_theme3.png
  presentation/src/main/res/drawable-hdpi/img_barcode.png
  presentation/src/main/res/drawable-hdpi/img_theme1.png
  presentation/src/main/res/drawable-hdpi/img_theme2.png
  presentation/src/main/res/drawable-hdpi/img_theme3.png
  presentation/src/main/res/drawable-mdpi/bg_theme1.png
  presentation/src/main/res/drawable-mdpi/bg_theme2.png
  presentation/src/main/res/drawable-mdpi/bg_theme3.png
  presentation/src/main/res/drawable-mdpi/img_barcode.png
  presentation/src/main/res/drawable-mdpi/img_theme1.png
  presentation/src/main/res/drawable-mdpi/img_theme2.png
  presentation/src/main/res/drawable-mdpi/img_theme3.png
  presentation/src/main/res/drawable-xhdpi/bg_theme1.png
  presentation/src/main/res/drawable-xhdpi/bg_theme2.png
  presentation/src/main/res/drawable-xhdpi/bg_theme3.png
  presentation/src/main/res/drawable-xhdpi/img_barcode.png
  presentation/src/main/res/drawable-xhdpi/img_theme1.png
  presentation/src/main/res/drawable-xhdpi/img_theme2.png
  presentation/src/main/res/drawable-xhdpi/img_theme3.png
  presentation/src/main/res/drawable-xxhdpi/bg_theme1.png
  presentation/src/main/res/drawable-xxhdpi/bg_theme2.png
  presentation/src/main/res/drawable-xxhdpi/bg_theme3.png
  presentation/src/main/res/drawable-xxhdpi/img_barcode.png
  presentation/src/main/res/drawable-xxhdpi/img_theme1.png
  presentation/src/main/res/drawable-xxhdpi/img_theme2.png
  presentation/src/main/res/drawable-xxhdpi/img_theme3.png
  presentation/src/main/res/drawable-xxxhdpi/bg_theme1.png
  presentation/src/main/res/drawable-xxxhdpi/bg_theme2.png
  presentation/src/main/res/drawable-xxxhdpi/bg_theme3.png
  presentation/src/main/res/drawable-xxxhdpi/img_barcode.png
  presentation/src/main/res/drawable-xxxhdpi/img_theme1.png
  presentation/src/main/res/drawable-xxxhdpi/img_theme2.png
  presentation/src/main/res/drawable-xxxhdpi/img_theme3.png
  presentation/src/main/res/drawable/bg_coupon_detail.xml
  presentation/src/main/res/drawable/bg_makecon_theme1.png
  presentation/src/main/res/drawable/btn_makeon_get.xml
  presentation/src/main/res/drawable/ic_left_arrow.xml
  presentation/src/main/res/drawable/ic_right_arrow.xml
  presentation/src/main/res/drawable/theme1.png
  presentation/src/main/res/layout/activity_buddy_con.xml
  presentation/src/main/res/layout/activity_make_coupon.xml
  presentation/src/main/res/layout/layout_appbar.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/text_style.xml
Labels: feature, design
